Repository protobom/protobom, pull requests merged in 2023-09, with the labels that each got.

#91 Add writer support for Authors
  pkg/writer/serializer_cdx.go
Labels: area/serializers

#80 Reader+Writer Integration Tests
  .github/workflows/go-build-and-test.yml
  Makefile
  go.mod
  go.sum
  hack/verify-fakes.sh
  internal/tools.go
  pkg/native/serializer.go
  pkg/native/serializers/serializer_cdx.go
  pkg/native/serializers/serializer_cdx14.go
  pkg/native/serializers/serializer_spdx23.go
  pkg/native/unserializer.go
  pkg/native/unserializers/unserializer_cdx14.go
  pkg/native/unserializers/unserializer_spdx23.go
  pkg/reader/implementation.go
  pkg/reader/reader.go
  pkg/reader/reader_test.go
  pkg/reader/readerfakes/fake_parser_implementation.go
  pkg/writer/implementation.go
  pkg/writer/writer.go
  pkg/writer/writer_test.go
  pkg/writer/writerfakes/fake_writer_implementation.go
Labels: area/tests

#81 Initial Conformance Framework Check-In
  Makefile
  test/conformance/README.md
  test/conformance/conformance_test.go
  test/conformance/generator/main.go
  test/conformance/testdata/spdx/2.3/json/curl.spdx.json
  test/conformance/testdata/spdx/2.3/json/curl.spdx.json.proto
Labels: area/tests

#87 Add README documenting scripts in ./hack
  hack/README.md
Labels: documentation

#88 Code of Conduct
  code-of-conduct.md
Labels: documentation

#90 Alpha SPDX 3.0 Serializer
  pkg/native/serializers/beta/serializer_spdx3.go
Labels: area/serializers

#94 Protobuf presubmit check
  .github/workflows/go-build-and-test.yml
  hack/README.md
  hack/common.sh
  hack/verify-fakes.sh
  hack/verify-proto.sh
Labels: area/tests

#96 CDX Serializer: Add Primary Purpose to Type unit test
  pkg/native/serializers/serializer_cdx_test.go
Labels: area/tests

#109 Return error if native serializer does not return valid root node
  pkg/native/serializers/serializer_cdx.go
Labels: bug
