Repository protobom/protobom, pull requests merged in 2023-08, with the labels that each got.

#51 chore: devcontainer / precommit hooks
  .devcontainer/devcontainer.json
  .devcontainer/post-create.sh
  .github/workflows/golangci-lint.yml
  .golangci.yaml
  .pre-commit-config.yaml
  CODEOWNERS
  README.md
  api/sbom.proto
  docs/cyclone-spdx-analysis.md
  docs/regenerate-protobuf.md
  docs/serializers.md
  docs/structure.md
  go.mod
  pkg/formats/testdata/linux-x64-manifest.spdx.json
  pkg/formats/testdata/nginx.spdx
  pkg/formats/testdata/pause.spdx
Labels: enhancement

#65 Fix purl and CPE retrieval and storage
  pkg/reader/unserializer_cdx14.go
  pkg/reader/unserializer_spdx23.go
  pkg/sbom/identifier.go
  pkg/sbom/node.go
  pkg/writer/serializer_cdx.go
  pkg/writer/serializer_spdx23.go
Labels: bug

#66 nodelist.GetMatchingNode()
  pkg/sbom/node.go
  pkg/sbom/nodelist.go
  pkg/sbom/nodelist_test.go
Labels: enhancement

#70 proto: Change identifier field to map
  api/sbom.proto
  pkg/formats/spdx/spdx.go
  pkg/reader/unserializer_cdx14.go
  pkg/reader/unserializer_spdx23.go
  pkg/sbom/identifier.go
  pkg/sbom/identifier_test.go
  pkg/sbom/node.go
  pkg/sbom/node_test.go
  pkg/sbom/nodelist.go
  pkg/sbom/nodelist_test.go
  pkg/sbom/sbom.pb.go
  pkg/writer/serializer_cdx.go
  pkg/writer/serializer_spdx23.go
Labels: enhancement

#61 docs: add devcontainer getting started
  docs/development.md
Labels: documentation

#36 sniffer cleanup
  pkg/formats/sniffer.go
  pkg/writer/serializer_cdx.go
Labels: enhancement
