Repository protobom/protobom, pull requests merged in 2023-12, with the labels that each got.

#127 Created CONTRIBUTOR.md file
  CONTRIBUTOR.md
  docs/development.md
Labels: documentation

#151 CycloneDX Fixes
  pkg/native/serializers/serializer_cdx.go
  pkg/native/serializers/serializer_cdx_test.go
  pkg/native/unserializers/unserializer_cdx.go
  pkg/native/unserializers/unserializer_cdx_test.go
  pkg/sbom/hashalgorithm.go
  test/conformance/testdata/cyclonedx/1.4/json/bom-1.4.json
  test/conformance/testdata/cyclonedx/1.4/json/bom-1.4.json.proto
Labels: bug, area/serializers, area/unserializers

#155 Bump CDX libraries to 0.8
  go.mod
  go.sum
  pkg/native/serializers/serializer_cdx.go
Labels: area/serializers

#156 Fix CycloneDX ExtRef Panic
  pkg/native/unserializers/unserializer_cdx.go
Labels: bug

#147 Add CycloneDX conformance samples
  test/conformance/conformance_test.go
  test/conformance/testdata/cyclonedx/1.4/bom-1.4.json.proto
  test/conformance/testdata/cyclonedx/1.4/json/bom-1.4.json.proto
  test/conformance/testdata/cyclonedx/1.4/json/juice-shop-11.1.2.cdx.json
  test/conformance/testdata/cyclonedx/1.4/json/juice-shop-11.1.2.cdx.json.proto
  test/conformance/testdata/cyclonedx/1.5/json/bom-1.5.json
  test/conformance/testdata/cyclonedx/1.5/json/bom-1.5.json.proto
  test/conformance/testdata/cyclonedx/1.5/json/syft-0.96.0_plone-5.2.cdx.json
  test/conformance/testdata/cyclonedx/1.5/json/syft-0.96.0_plone-5.2.cdx.json.proto
  test/conformance/testdata/cyclonedx/1.5/json/syft-0.96.0_rails-5.0.0.cdx.json
  test/conformance/testdata/cyclonedx/1.5/json/syft-0.96.0_rails-5.0.0.cdx.json.proto
  test/conformance/testdata/spdx/2.3/json/bom-v0.4.1_cirros-0.4.0.spdx.json.proto
  test/conformance/testdata/spdx/2.3/json/curl.spdx.json.proto
Labels: area/tests
