Repository protobom/protobom, pull requests merged in 2023-10, with the labels that each got.

#119 Streamline and colorize README examples
  README.md
Labels: documentation

#121 Update Supported Formats and Version Table
  README.md
Labels: documentation

#134 Bump protobom to go to 1.21
  .github/workflows/golangci-lint.yml
  go.mod
  go.sum
Labels: dependencies

#140 Graph API improvements
  README.md
  pkg/sbom/edge.go
  pkg/sbom/node.go
  pkg/sbom/node_test.go
  pkg/sbom/nodelist.go
  pkg/sbom/nodelist_test.go
Labels: enhancement, area/tests, go, area/graph
